# Generated by Django 5.0.4 on 2024-04-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_storage_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
